trainer:
  default_root_dir: null
  default_hdfs_dir: hdfs://harunasg/home/byte_magellan_govern/users/xiaochen.qiu/modelzoo_text_clf/
  logger: true
  log_every_n_steps: 50
  benchmark: false
  enable_speedmonitor: true
  enable_versions: true
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 2
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: true
  sync_fit_metrics: null
  val_check_interval: 0.5
  accumulate_grad_batches: null
  gradient_clip_val: 2.0
  seed: 42
  summarize_model_depth: 2
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: loss
  checkpoint_mode: min
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  enable_trace: false
model:
  pretrained_model_name_or_path: xlm-roberta-base
  classification_task_enable: false
  classification_task_head: 2
  hidden_size: 768
  load_pretrain: null
  all_gather_limit: -1
  warmup_ratio: 0.1
  weight_decay: 0.01
  base_lr: 0.00005
  warmup_lr: 5.0e-07
  min_lr: 5.0e-06
  lr_scheduler: cosine
  lr_scheduler_decay_ratio: 0.8
  lr_scheduler_decay_rate: 0.1
  optimizer: adamw
  optimizer_betas: [0.9, 0.999]
  optimizer_eps: 1.0e-08
  momentum: 0.9
data:
  train_batch_size: 16
  val_batch_size: 16
  data_size: 16000
  val_step: -1
  num_workers: 1
  tokenizer: xlm-roberta-base
  train_file: 'hdfs://harunava/home/byte_magellan_va/user/jiangjunjun.happy/xtreme_ecom/ansa_train.json'
  val_file: 'hdfs://harunava/home/byte_magellan_va/user/jiangjunjun.happy/xtreme_ecom/leaderboard/ansa_test.json'
  x_key: text
  y_key: label
  region_key: country
  pre_tokenize: false
  max_len: 256
log_level: INFO
