class_num: 130

freeze_prefix: []

weight_decay: 0.01
lr_scheduler: cosine #cosine, linear, step
base_lr: 1.0e-4
warmup_lr: 1.0e-6
min_lr: 1.0e-6
warmup_epochs: 5
lr_scheduler_decay_epochs: 30
lr_scheduler_decay_rate: 0.1

optimizer: adamw
optimizer_eps: 1.0e-8
momentum: 0.9

temp: 0.07
queue_size: 65536
momentum_update: 0.995
alpha: 0.4