trainer:
  default_root_dir: /mnt/bn/multimodel-pretrain/scripts/cruise_logs/pretrain_test_0403
  default_hdfs_dir: null
  logger: true
  log_every_n_steps: 20
  benchmark: false
  enable_speedmonitor: true
  enable_versions: true
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: 16
  max_epochs: 20
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: true
  sync_fit_metrics: null
  val_check_interval: 1.0
  accumulate_grad_batches: null
  gradient_clip_val: null
  seed: null
  summarize_model_depth: 5
  resume_ckpt_path: null
  resume_loader_state: false
  callbacks: null
  enable_checkpoint: 30
  checkpoint_monitor: val_loss
  checkpoint_mode: min
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  experiment_name: null
  enable_trace: false
  reload_dataloaders_every_n_epochs: -1
  strategy: ddp
  enable_qat: false
  qat_kwargs: {}
  optimizer_kwargs:
    optimizer:
      type: torch.optim.AdamW
      params:
        lr: 0.0001
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-06
        weight_decay: 0.01
        correct_bias: true
        correct_bias_eps: false
        bias_correction: true
        adam_w_mode: true
        amsgrad: false
        set_grad_none: true
        momentum: 0.0
        nesterov: false
    scheduler:
      type: cruise.optim.constant_lr
      total_steps_param_name: total_iters
      warmup_steps_param_name: warmup_iters
      interval: epoch_end
      params:
        warmup_step_rate: 0.0
        start_factor: 0.3333333333333333
        end_factor: 1.0e-07
        num_cycles: 0.5
        lr_end: 1.0e-07
        power: 1.0
  grad_norm_layers: []
model:
  config_model: ./examples/fashion_vtp/pretrain_configs/config_model.yaml
  config_optim: ./examples/fashion_vtp/pretrain_configs/config_optim.yaml
  load_pretrained: hdfs://haruna/home/byte_ecom_govern/user/yangmin.priv/1e_fvtp3_continue_pretrain_0220_8new/model_state_epoch_1508298.th
data:
  # train_path: /mnt/bd/video-text-pretrain/samples_all/meta/train
  # val_path: /mnt/bd/video-text-pretrain/samples_all/meta/val
  train_path: /mnt/bn/ecology-multimodal-benchmark/hq_live_data/meta/train
  val_path: /mnt/bn/ecology-multimodal-benchmark/hq_live_data/meta/val
  vocab_file: hdfs://haruna/home/byte_search_nlp_lq/multimodal/modelhub/albert_6l_zh_mix_oldcut_20200921/archer/zh_old_cut_145607.vocab
  train_batch_size: 8
  val_batch_size: 8
  num_workers: 4
  # train_data_size: 93606912
  # val_data_size: 3237888
  train_data_size: 158028
  val_data_size: 19995
  ocr_max_len: 40
  asr_max_len: 360
  frame_len: 5
log_level: INFO
