trainer:
  default_root_dir: wanli.0815/experiments/lm_pretrain/item_ccr_model/outputs/logs
  default_hdfs_dir: hdfs://haruna/home/byte_ecom_govern/user/wanli.0815/experiments/pretrain/ccr_item_raw_model/outputs
  logger: true
  log_every_n_steps: 100
  benchmark: false
  enable_speedmonitor: true
  enable_versions: false
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 5
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: false
  sync_fit_metrics: null
  val_check_interval:
  - 10000
  - 1.0
  accumulate_grad_batches: null
  gradient_clip_val: null
  seed: null
  summarize_model_depth: 2
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: val_loss
  checkpoint_mode: min
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  experiment_name: null
  enable_trace: false
model:
  learning_rate: 0.0002
  weight_decay: 0.1
  warmup_steps: 10000
  pretrain_model_name: /mnt/bn/wanli/resources/pretrained_lm/chinese_deberta_base_L6
  cl_enable: false
  cl_weight: 10.0
  ntx_enable: true
  all_gather_limit: -1
  classification_task_enable: false
  cls_weight: 1.0
  cls_class_num: 2
  sce_loss_enable: false
  auc_score_enable: false
  partial_load_from_checkpoints_path: null
  multi_label_enable: false
  multi_label_map_file: ''
  multi_label_threshold: 0.5
  hidden_size: 768
  hf_enable: false
  vocab_file_path: /mnt/bn/wanli/resources/vocabulary/chinese_deberta_base_L6_vocab.txt
data:
  train_batch_size: 64
  val_batch_size: 64
  train_paths: hdfs://haruna/home/byte_ecom_govern/user/wanli.0815/experiments/pretrain/ccr_item_model/data/train_data_v1/part*
  val_paths: hdfs://haruna/home/byte_ecom_govern/user/wanli.0815/experiments/pretrain/ccr_item_model/data/valid_data_v1/part*
  data_size: 190000000
  val_step: 0
  classification_task_enable: false
  text_label_field: label
  text_field: text
  cl_enable: false
  num_workers: 0
  context_length: 128
  mlm_probability: 0.15
  key_span_file_path: ''
  max_forward_search_step: 6
  multi_label_enable: false
  multi_label_map_file: ''
  multi_label_split_token: ','
  vocab_file_path: /mnt/bn/wanli/resources/vocabulary/chinese_deberta_base_L6_vocab.txt
  pretrain_model_name: /mnt/bn/wanli/resources/pretrained_lm/chinese_deberta_base_L6
log_level: INFO
