deepspeed: valley/configs/deepspeed/config_zero2.json
model_class: valley-product
model_name_or_path: /mnt/bn/yangmin-priv-fashionmm/Data/sk/checkpoints/valley-chinese-7b-merge-product-continue-pretrain-down-pool-5epoch-v2/checkpoint-12000
data_path: /mnt/bn/yangmin-priv-fashionmm/Data/wuji/data_process/new_process/train_data/train_data_v12_dup_neg_and_pos_valley_product.json
image_folder: /mnt/bn/yangmin-priv-fashionmm/Data/wuji/big_model_train_image_data
output_dir: /mnt/bn/yangmin-priv-fashionmm/Data/wuji/data_process/new_process/product_checkpoints/data-ys-v3-valley-product-7b-jinshou-class-lora-multi-class
project_name: jinshou_valley_product
run_name: jinshou_class
# english or chinese, default is english
language: chinese
vision_tower: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese-clip-vit-large-patch14
version: "v0"
prompt_version: "jinshou_cot"
only_mask_system: False
mm_vision_select_feature: 'cls_patch'
mm_vision_select_layer: -2
mm_use_im_start_end: True
mm_use_im_patch_token: False
mm_projector_type: pool_adapter
pool_out_size: 8
max_img_num: 12
tune_mm_mlp_adapter: True
freeze_backbone: True
group_by_modality_length: True
bf16: False
fp16: True
lora_enable: True
num_train_epochs: 6
per_device_train_batch_size: 3
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
evaluation_strategy: "no"
save_strategy: "no"
lora_save_strategy: "steps"
save_steps: 5000
learning_rate: 5e-5
weight_decay: 0.
warmup_ratio: 0.
lr_scheduler_type: cosine
logging_steps: 1
tf32: False
model_max_length: 2048
gradient_checkpointing: True
dataloader_num_workers: 4
lazy_preprocess: True
report_to: wandb