model_class: valley-video
deepspeed: valley/configs/deepspeed/config_zero3.json
model_name_or_path: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese_valley_belle7b
data_path: /mnt/bn/yangmin-priv-fashionmm/projects/zhaoziwang/data/jinshou_data/demodata7.json
image_folder: /mnt/bn/yangmin-priv-fashionmm/projects/zhaoziwang/data/jinshou_data/
# experiment name
project_name: chinese-valley-toy
run_name: toy
# xl or chinese, default is xl
language: chinese
vision_tower: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese-clip-vit-large-patch14
version: "v0"
prompt_version: "belle"  
only_mask_system: False
mm_vision_select_feature: 'cls_patch'
mm_vision_select_layer: -2
mm_use_im_start_end: True
mm_use_im_patch_token: False
tune_mm_mlp_adapter: True
freeze_backbone: True
group_by_modality_length: True
bf16: False
fp16: True
lora_enable: True
output_dir: /mnt/bn/yangmin-priv-fashionmm/Checkpoints/toy_valley_belle7b_lora_zero3
num_train_epochs: 3
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
gradient_accumulation_steps: 1
evaluation_strategy: "no"
save_strategy: "no"
lora_save_strategy: "steps"
save_steps: 500
learning_rate: 5e-4
weight_decay: 0.
warmup_ratio: 0.00
lr_scheduler_type: cosine
logging_steps: 1
tf32: False
model_max_length: 2048
gradient_checkpointing: True
dataloader_num_workers: 4
lazy_preprocess: True
report_to: wandb