deepspeed: valley/configs/deepspeed/config_zero3.json
model_class: valley-product
model_name_or_path: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese_valley_product_belle7b_pool_adapter
data_path: /mnt/bn/yangmin-priv-fashionmm/wangzhen/data/redirect/cot_train_gpt4_mixed_prompt_fit.json
project_name: toy
run_name: valley-pool_adapter-sft-demo
# english or chinese, default is english
language: chinese
vision_tower: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese-clip-vit-large-patch14
version: "v0"
prompt_version: "belle"
only_mask_system: False
mm_vision_select_feature: 'cls_patch'
mm_vision_select_layer: -2
mm_use_im_start_end: True
mm_use_im_patch_token: False
mm_projector_type: pool_adapter
pool_out_size: 8
max_img_num: 8
tune_mm_mlp_adapter: True
freeze_backbone: True
group_by_modality_length: True
bf16: False
fp16: True
lora_enable: True
output_dir: /mnt/bn/yangmin-priv-fashionmm/Checkpoints/toy_yinliu_valley_product_belle7b_lora_zero3
num_train_epochs: 5
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 1
evaluation_strategy: "no"
save_strategy: "no"
lora_save_strategy: "steps"
save_steps: 1000
learning_rate: 0.0001
weight_decay: 0.
warmup_ratio: 0.00
lr_scheduler_type: cosine
logging_steps: 1
tf32: False
model_max_length: 2048
gradient_checkpointing: True
dataloader_num_workers: 4
lazy_preprocess: True
report_to: wandb