trainer:
  default_root_dir: /mnt/bn/ecom-govern-maxiangqian/qingxuan/EasyGuard/examples/high_quality_live/save_model/v1_train16w_baseline_new_frame_netvlad_arcloss
  default_hdfs_dir: null
  logger: true
  log_every_n_steps: 50
  benchmark: false
  enable_speedmonitor: true
  enable_versions: false
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 15
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: false
  sync_fit_metrics: null
  val_check_interval: 1.0
  accumulate_grad_batches: null
  gradient_clip_val: 1.0
  seed: null
  summarize_model_depth: 3
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: 15
  checkpoint_monitor: step
  checkpoint_mode: max
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: hq_live_qx
  experiment_name: baseline_16w_new_frame_netvlad_arcloss
  enable_trace: false
  reload_dataloaders_every_n_epochs: -1
model:
  config_text: /mnt/bn/ecom-govern-maxiangqian/qingxuan/EasyGuard/examples/high_quality_live/config/config_text.yaml
  config_visual: /mnt/bn/ecom-govern-maxiangqian/qingxuan/EasyGuard/examples/high_quality_live/config/config_visual.yaml
  config_fusion: /mnt/bn/ecom-govern-maxiangqian/qingxuan/EasyGuard/examples/high_quality_live/config/config_fusion.yaml
  # learning_rate: 0.01
  # weight_decay: 0.0001
  learning_rate: 0.00004
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.02
  lr_warmup_steps_weight: 0.3
#  load_pretrained: hdfs://haruna/home/byte_ecom_govern/user/liuyuhang/pretrain/fashion_bert_v2/model_state_epoch_83332.th
  use_text_modal: true
  use_visual_modal: true
  use_multilabel: false
  use_arcface: true
data:
  train_files: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/hq_live/packed_data/20221001_20221102/v1_1/train_balance_16w
#  train_files: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/authentic/packed_data/20221011_20221012/v1_debug/test
  val_files: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/hq_live/packed_data/20221103_20221106/v1_test/test2w
  train_batch_size: 16
  val_batch_size: 8
  num_workers: 16
  max_len: 512
  frame_len: 4
  vocab_file: hdfs://haruna/home/byte_search_nlp_lq/multimodal/modelhub/albert_6l_zh_mix_oldcut_20200921/archer/zh_old_cut_145607.vocab

log_level: INFO
