trainer:
  default_root_dir: null
  default_hdfs_dir: null
  logger: true
  log_every_n_steps: 50
  benchmark: false
  enable_speedmonitor: true
  enable_versions: false
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 30
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: true
  sync_fit_metrics: null
  val_check_interval: 100.0
  accumulate_grad_batches: null
  gradient_clip_val: 2.0
  seed: null
  summarize_model_depth: 3
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: loss
  checkpoint_mode: min
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: false
  project_name: authentic
  experiment_name: predict
  enable_trace: false
  reload_dataloaders_every_n_epochs: -1
model:
  config_text: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/hq_live/config/config_text.yaml
  config_visual: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/hq_live/config/config_visual.yaml
  config_fusion: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/hq_live/config/config_fusion.yaml
  learning_rate: 0.0001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.02
  load_pretrained: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/hq_live/model/v1_train12w_baseline_1107/checkpoints/epoch=10-step=12364-loss=0.278.ckpt
  use_text_modal: true
  use_visual_modal: true
data:
  train_files: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/authentic/packed_data/20220826_20220917/v1_0/train_70w
#  train_files: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/authentic/packed_data/20221011_20221012/v1_debug/test
  val_files: /mnt/bn/ecom-govern-maxiangqian/liuzeyu/authentic/packed_data/20221011_20221012/v1_debug/test
  train_batch_size: 10
  val_batch_size: 4
  num_workers: 16
  max_len: 256

log_level: INFO
