wandb_version: 1

_name_or_path:
  desc: null
  value: /mnt/bn/yangmin-priv-fashionmm/Data/sk/checkpoints/valley-chinese-7b-merge-product-continue-pretrain-down-pool-5epoch-v2/checkpoint-12000
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - ValleyProductLlamaForCausalLM
attention_bias:
  desc: null
  value: false
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bits:
  desc: null
  value: 16
bos_token_id:
  desc: null
  value: 1
cache_dir:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
cross_attention_hidden_size:
  desc: null
  value: null
data_seed:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 4
dataloader_pin_memory:
  desc: null
  value: true
ddp_backend:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: []
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: valley/configs/deepspeed/config_zero2.json
disable_tqdm:
  desc: null
  value: false
dispatch_batches:
  desc: null
  value: null
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
double_quant:
  desc: null
  value: true
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 2
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: null
evaluation_strategy:
  desc: null
  value: 'no'
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
freeze_backbone:
  desc: null
  value: true
freeze_mm_mlp_adapter:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
generation_config:
  desc: null
  value: null
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: true
gradient_checkpointing_kwargs:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
group_by_length:
  desc: null
  value: false
group_by_modality_length:
  desc: null
  value: true
half_precision_backend:
  desc: null
  value: auto
hidden_act:
  desc: null
  value: silu
hidden_size:
  desc: null
  value: 4096
hub_always_push:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: null
  value: false
image_aspect_ratio:
  desc: null
  value: square
image_grid_pinpoints:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
include_tokens_per_second:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 11008
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
language:
  desc: null
  value: chinese
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /mnt/bn/yangmin-priv-fashionmm/Data/wuji/data_process/new_process/product_checkpoints/data-mutli-v5-valley-7b-jinshou-class-lora-multi-class/runs/Feb26_11-47-33_n128-103-028
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 1
logging_strategy:
  desc: null
  value: steps
lora_alpha:
  desc: null
  value: 32
lora_bias:
  desc: null
  value: none
lora_dropout:
  desc: null
  value: 0.05
lora_enable:
  desc: null
  value: true
lora_r:
  desc: null
  value: 16
lora_save_strategy:
  desc: null
  value: steps
lora_weight_path:
  desc: null
  value: ''
lr_scheduler_type:
  desc: null
  value: cosine
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_position_embeddings:
  desc: null
  value: 2048
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: null
min_length:
  desc: null
  value: 0
mm_hidden_size:
  desc: null
  value: 1024
mm_projector_lr:
  desc: null
  value: null
mm_projector_type:
  desc: null
  value: pool_adapter
mm_use_im_patch_token:
  desc: null
  value: false
mm_use_im_start_end:
  desc: null
  value: true
mm_vision_select_feature:
  desc: null
  value: cls_patch
mm_vision_select_layer:
  desc: null
  value: -2
mm_vision_tower:
  desc: null
  value: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese-clip-vit-large-patch14
model_max_length:
  desc: null
  value: 2048
model_type:
  desc: null
  value: valley
mp_parameters:
  desc: null
  value: ''
neftune_noise_alpha:
  desc: null
  value: null
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 32
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_hidden_layers:
  desc: null
  value: 32
num_key_value_heads:
  desc: null
  value: 32
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 6
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: /mnt/bn/yangmin-priv-fashionmm/Data/wuji/data_process/new_process/product_checkpoints/data-mutli-v5-valley-7b-jinshou-class-lora-multi-class
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 1
per_device_train_batch_size:
  desc: null
  value: 3
per_gpu_eval_batch_size:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
pool_out_size:
  desc: null
  value: 8
predict_with_generate:
  desc: null
  value: false
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
pretraining_tp:
  desc: null
  value: 1
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
quant_type:
  desc: null
  value: nf4
ray_scope:
  desc: null
  value: last
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value:
  - wandb
resume_from_checkpoint:
  desc: null
  value: null
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
rms_norm_eps:
  desc: null
  value: 1.0e-06
rope_scaling:
  desc: null
  value: null
rope_theta:
  desc: null
  value: 10000.0
run_name:
  desc: null
  value: jinshou_class
save_on_each_node:
  desc: null
  value: false
save_safetensors:
  desc: null
  value: true
save_steps:
  desc: null
  value: 5000
save_strategy:
  desc: null
  value: 'no'
save_total_limit:
  desc: null
  value: null
seed:
  desc: null
  value: 42
sep_image_conv_front:
  desc: null
  value: false
sep_token_id:
  desc: null
  value: null
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
split_batches:
  desc: null
  value: false
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: false
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
torch_dtype:
  desc: null
  value: float16
torchdynamo:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
transformers_version:
  desc: null
  value: 4.35.0
tune_mm_mlp_adapter:
  desc: null
  value: true
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mm_proj:
  desc: null
  value: true
use_mps_device:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 79480
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
