vocab_size: 145608
embedding_size: 256
num_hidden_layers: 6
hidden_size: 768
intermediate_size: 3072
num_attention_heads: 12
project_embedding_first: false
max_position_embeddings: 512
type_vocab_size: 16
hidden_dropout_prob: 0.1
need_visual_ln: true
max_frame_num: 16
visual_front: false
with_pooler: true
initializer_range: 0.02
visual_dim: 512
visual_type: SwinB224
layernorm_eps: 0.00001
freeze_prefix: []
